### PR TITLE
Add features page

### LINKED ISSUE #5: Separate landing page and feature list
Currently all of our features are presented on the main page. It's better to leave the main page for top highlights, and add a detailed manual as a separate page. 

Main page should answer the question "why should I try this?" and should mention: 

  * wip status
  * native analysis engine 
  * navigation facilities (both go to definition and go to symbol)
  * completion facilities 

Manual should answer the question "how can I be the most productive?" and should go into great detail about each feature, even if it is small.

### PR DESCRIPTION
**Pull request by matklad**
Fixes #5

@jajakobyly any suggestions/corrections?

### CODE REVIEW

**Comment by jajakobyly** [comment]
Hmm the idea is nice, I approve it, though instead of docs page, I'd set up separate, more stylish features page (maybe something similar to [IntelliJ's one](https://www.jetbrains.com/idea/features/) or maybe [PyCharm's one](https://www.jetbrains.com/pycharm/features/); IntelliJ's solution might play well with GIFs actually)

Also instead of leaving completion and part of navigation on the front page, what do you think about putting there only some standard copy, and move all feature-related stuff to separate page?

**Comment by jajakobyly** [comment]
> Will it be markdown based?

You can freely put html in `*.markdown` files. I am able to make some nice layout requiring only two `<div>`s for each section.

> So instead of listing shortcuts, we will give a screenshot and just say that the navigation is awesome (because it is!)?

I need to investigate this idea further, but what about embedding small videos hosted on [gfycat](https://gfycat.com/)?

**Comment by matklad** [comment]
> I am able to make some nice layout requiring only two <div>s for each section.

We should try this. 

>I need to investigate this idea further, but what about embedding small videos hosted on gfycat? At least on Windows, making such ones is damn easy with ShareX.

Sound interesting, but let's first create this "highlights / reference docs" split.

**Comment by matklad** [comment]
Reminder to self: document https://github.com/intellij-rust/intellij-rust/commit/fee66441ef9891aa1ed5b4d39f674cdf9c4ee2a3

**Comment by jajakobyly** [comment]
BTW I'll allow myself to push here

**Comment by jajakobyly** [comment]
current state of development (_What is..._ section and features page are yet to be done):
intellij-rust 2016-07-17 15-55-28

**Comment by jajakobyly** [comment]
@matklad done
intellij-rust 2016-07-17 20-39-13

Features page hasn't changed a lot, apart from there are now normal-page-style headers (uppercase ones)

**Comment by matklad** [comment]
What are your plans for the feature page?

**Comment by jajakobyly** [comment]
I have no strong idea yet, unfortunately. Maybe something like https://www.jetbrains.com/idea/features/ (layout)

**Pull request merged**
