### PR TITLE
Changelog 101: Embed GIFs

### PR DESCRIPTION
**Pull request by ozkriff**
I believe that posts look better with embedded images. These gifs aren't really _that_ heavy and it seems to work fine with mobile browsers.

Some gifs are too large so I've used a raw `img` tag with an explicit `width` property.

### CODE REVIEW

**Comment by Undin** [comment]
@ozkriff Thanks for PR!
Unfortunately, the current implementation has a drawback - all gifs are played at the same time.
I'd prefer to show only previews with button to launch the corresponding gif (as we do at features page). For example, all JetBrains blog posts use the described approach.
But it doesn't seem hard to implement as we already have necessary js scripts.
I suggest not to change existing changelogs because it will require some additional work and almost nobody will see the result of such changes. But we will try this approach for next posts

**Comment by Undin** [comment]
@ozkriff What do you think about embedded gif the latest [changelog](https://intellij-rust.github.io/2019/08/12/changelog-103.html)?

**Comment by ozkriff** [comment]
It's nice! :)

Btw, it has some size issues on my phone:
image

**Comment by Undin** [comment]
> It's nice! :)

🎉 

> Should I open an issue for that?

Check it again, please. Looks like I've fixed it

**Comment by ozkriff** [comment]
> Check it again, please. Looks like I've fixed it

Nope, nothing changed for me

**Comment by Undin** [comment]
> Nope, nothing changed for me

@ozkriff Hm, it's weird. I've checked it in mobile Chrome and Safary on several devices and now I don't see described problem.
Could you check again and file an issue in case if the problem still reproducible for you?

**Comment by Undin** [comment]
I think it can be closed

**Pull request closed without merging**
