### PR TITLE
Update quick start

### PR DESCRIPTION
**Pull request by Undin**
* new `Create new project` section
* steps for small IDEs

### CODE REVIEW

**Comment by Undin** [comment]
@matklad or @mkaput r?

**Comment by matklad** [comment]
Let’s use CLion EAP instead of pycharm?

**Comment by Undin** [comment]
> Let’s use CLion **EAP** instead of pycharm?

Hm, I've read only half of the message again 🤦
Ok, if you think that it's ok let's do it)

**Comment by Undin** [comment]
@matklad done

**Pull request merged**
