### PR TITLE
"Beautiful" features page

### PR DESCRIPTION
**Pull request by jajakobyly**
Inspiration:
https://www.jetbrains.com/clion/features/
https://www.jetbrains.com/pycharm/features/

Sorry @matklad for not using Markdown, but Jekyll refuses to render it when there is too much HTML :stuck_out_tongue_winking_eye: 

This guy should fix intellij-rust/intellij-rust#522

### CODE REVIEW

**Comment by jajakobyly** [comment]
Actual screenshot

features 2016-07-23 20-25-59

**Comment by matklad** [comment]
Looks spectacularly! The only thing that concerns me is the columnar layout. I would like to add screenshots/gifs/videos to every small feature. This seem to be at odds with the current layout.

Or perhaps this gifs should be done in the popup fashion?

**Comment by jajakobyly** [comment]
features 2016-07-24 14-42-00

**Comment by jajakobyly** [comment]
Pics for live templates are gfys :smile: Also I had to "fake" example run configuration, as we don't have automatic creation of such run configs :disappointed:

**Comment by matklad** [comment]
> as we don't have automatic creation of such run configs

I don't quite understand, this bullet is about exactly this automatically created run configs :) Do you mean that you had to specify the name manually? All the rest should be done automatically

**Comment by jajakobyly** [comment]
> I don't quite understand, this bullet is about exactly this automatically created run configs :) Do you mean that you had to specify the name manually? All the rest should be done automatically 

I had to manually create whole run config, as it wasn't automagically suggested

**Comment by matklad** [comment]
Sounds like a bug. It should work like this: https://zippy.gfycat.com/OrderlyOrangeCricket.webm. 

Hm, you were trying to run a `main` from the `example`, right? I think I have not handled that case.

**Comment by matklad** [comment]
Oups, sorry for pushing changelog here :sweat_smile: , will force push it out of this PR

**Comment by matklad** [comment]
>Sounds like a bug.

Fixed in https://github.com/intellij-rust/intellij-rust/commit/45a100a64eccbc2b717c62fa48232350a59ebb8e

**Comment by jajakobyly** [comment]
Ok ready to go imho. Latest screen is in the 2nd comment. I didn't know how to record `Expand module` because of intellij-rust/intellij-rust#553. Also there is some strange gfycat embedding script bug making some gfys randomly not playable. I don't know what's going on there.

**Comment by matklad** [comment]
Fabulous!

**Pull request merged**
